# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: alicepi_proto/vad.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'alicepi_proto/vad.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x61licepi_proto/vad.proto\x12\x0b\x61licepi.vad\"\xaa\x02\n\tVadPacket\x12\x14\n\x0ctimestamp_ms\x18\x01 \x01(\x04\x12-\n\x05\x61udio\x18\x02 \x01(\x0b\x32\x1c.alicepi.vad.VadPacket.AudioH\x00\x12/\n\x06status\x18\x03 \x01(\x0e\x32\x1d.alicepi.vad.VadPacket.StatusH\x00\x1aN\n\x05\x41udio\x12\x13\n\x0bsample_rate\x18\x01 \x01(\r\x12\x10\n\x08\x63hannels\x18\x02 \x01(\r\x12\x10\n\x08sequence\x18\x03 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\"L\n\x06Status\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x13\n\x0fSPEECH_DETECTED\x10\x01\x12\x13\n\x0fSPEECH_HANGOVER\x10\x02\x12\x0b\n\x07SILENCE\x10\x03\x42\t\n\x07payloadb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'alicepi_proto.vad_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VADPACKET']._serialized_start=41
  _globals['_VADPACKET']._serialized_end=339
  _globals['_VADPACKET_AUDIO']._serialized_start=172
  _globals['_VADPACKET_AUDIO']._serialized_end=250
  _globals['_VADPACKET_STATUS']._serialized_start=252
  _globals['_VADPACKET_STATUS']._serialized_end=328
# @@protoc_insertion_point(module_scope)
